kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: damberg-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 443
          name: web
          protocol: TCP
        readinessProbe:
          httpGet:
            port: web
            path: /