apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: damberg-dev
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000
  selector:
    app: react-docker